### ISSUE TITLE
Needs moar documentation

### ISSUE THREAD

**Issue by lexi-lambda** [NHHSRoboticsClub/create-code-generator#1]
So what does this do?

```
STR
FUL
DRD _MX1 _MX2 _MX1 _MX2
WAT 20
DRD _NUL _NUL _NUL _NUL
```

It would be nice to have some opcode documentation. A simple markdown file documenting each opcode would be sufficient.

**Comment by birgelee** [comment]
I will put up a simple doc of the opt codes.  They are all fully documented by number in the create open interface.

In short that program translates to:
STR : start program (needed to begin all programs)
FUL : enable full mode.  needed for full functionality
DRD : Drive direct.  followed by wheel speeds
WAT : wait followed by the number of decaseconds 
_NUL : a value code that translates to 0
